### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by fenhl** [racetimeGG/racetime-app#216]
It would be nice to have the website adjust its color scheme based on [the `prefers-color-scheme` media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme). This is especially useful for people with visual impairments that make light text on dark backgrounds hard to read, but also just more comfortable in bright environments.

I attempted to implement this myself but ran into an issue where I was unsure about the intentions behind some uses of some colors. Therefore, I think a good first step would be to extract all colors into CSS variables, which can then be customized based on the `prefers-color-scheme` value. Here's an example from my previous attempt:

```css
:root {
    --accent1: #1da674;
    --accent2: #26dd9a;
    --accent3: #a6ebc4;
    --accent4: #beebd1;
    --background: #25272c;
    --background-gradient: #36393f;
    --best-time: #ebdfbe;
    --button: #0c0f14;
    --comment-background: #18191d;
    --comment-border: #17181b;
    --container: #212328;
    --danger-accent: #f08080;
    --disabled: #666;
    --footer: #999699;
    --foreground: #1a1c20;
    --go-gold: #e6c762;
    --layout-form-bottom: #111;
    --message-time: #aaa;
    --monitor-action-hover: #3b4b47;
    --muted: #ddd8dd;
    --placeholder: #8c898c;
    --positive: #a0e9a0;
    --race-status1: #1e1f24;
    --race-status2: #191a1e;
    --row: #08090a;
    --supporter1: #cca32a;
    --supporter2: #ffea99;
    --text: white;
    --title1: #becccc;
    --title2: #eee;
}

@media (prefers-color-scheme: light) {
    :root {
        --accent1: #1da674;
        --accent2: #26dd9a;
        --accent3: #a6ebc4;
        --accent4: #beebd1;
        --background: #ddd8dd;
        --background-gradient: #ccc6ca;
        --best-time: #ebdfbe;
        --button: #ebeef3;
        --comment-background: #e8e7e3;
        --comment-border: #e9e8e5;
        --container: #dedcd8;
        --danger-accent: #f08080;
        --disabled: #aaa;
        --footer: #999699;
        --foreground: #f9fbff;
        --go-gold: #e6c762;
        --layout-form-bottom: #eee;
        --message-time: #666;
        --monitor-action-hover: #b3a3a8;
        --muted: #25272c;
        --placeholder: #8c898c;
        --positive: #a0e9a0;
        --race-status1: #e1e0db;
        --race-status2: #e6e5e1;
        --row: #f8f7f5;
        --supporter1: #cca32a;
        --supporter2: #ffea99;
        --text: black;
        --title1: #413333;
        --title2: #111;
    }
}
```
